spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.operis.guard: INFO

app:
  cors:
    allowed-origins:
      - https://gustavohub.com
      - https://www.gustavohub.com
  initializer:
    enabled: false
